<a href="https://colab.research.google.com/github/GaboCg/personal-blog/blob/master/A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ayudantía 1 

**Magister en Finanzas** 

**Autor**: *Gabriel Cabrera  G.*

**Fecha**: 12 de Agosto del 2019

# Condicionales, Loops y otros *Control Flow*

1. Construya la siguiente secuencia de números incluyendo los None: *1, 2, None, 4, 5, 6, None*. Luego utilizando un loop sume los elemenos que son númericos (no considerar None).

In [0]:
seq_a = [1, 2, None, 4, 5, 6, None] 
valor = 0

for i in range(len(seq_a)):
    if seq_a[i] != None:
        valor += seq_a[i]

valor

18

2. Construya la siguiente secuencia de números: *1, 2, 3, 4, 5, 6, 7*. Luego utilizando un loop sume los elemenos menores al número 5.

In [0]:
seq_b = list(range(1, 8, 1))
total_hasta_5 = 0
   
for i in seq_b:
    if i == 5:
        break
    total_hasta_5 += i

total_hasta_5

10

3. Sume todo los números desde 0 hasta 99.999 que sean múltiplos de 3 o 5.   

In [0]:
suma = 0

for i in range(100000):
    if i % 3 == 0 or i % 5 == 0:
        suma += 1
        
suma

46667

# Funciones

1. Construya una función que para un número n entregue como output la suma de los cuadrados de $1^2 + 2^2 + 3^2 + 4^2 + ... + n^2$.

In [0]:
def elevado(n):
    numero = list(range(1, n+1))
    suma = 0
    for i in numero:
        suma += i**2
    return suma    

elevado(1)
elevado(3)
elevado(5)

55

2. Contruya una función que entregue como output si un número es o no divisible por 2.

In [0]:
def divisible(n):
    if n % 2 is 0:
        print("Es dividible")
    else:
        print("No es divisible")

divisible(2)

Es dividible


3. Construya una función que entregue la media aritmética o media geométrica de un conjunto de datos.

In [0]:
def media_aritmetica(x):
    return sum(x)/len(x)

# tener presente el uso de python 2.x, debe ser float. e.g type(3/3) int, en python 3.x es float
datos = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
media_aritmetica(datos)

3.5

# Introducción a Numpy 

## Ejercicios Básicos

1. Genere la siguiente matriz:

    $$
    A = \begin{pmatrix}
    3 & 0 & 2 \\
    2 & 0 & 2 \\
    0 & 1 & 1
    \end{pmatrix}
    $$

In [0]:
import numpy as np
from numpy.linalg import inv

A = np.array([3, 0, 2, 2, 0, 2, 0, 1, 1]).reshape(3,3)

2. Encuentre la transpuesta de la matriz A.

In [0]:
A.T
np.transpose(A)

array([[3, 2, 0],
       [0, 0, 1],
       [2, 2, 1]])

3. Encuentre la matriz inversa de A.

In [0]:
inv(A)

array([[ 1. , -1. ,  0. ],
       [ 1. , -1.5,  1. ],
       [-1. ,  1.5,  0. ]])

4. Genere las siguientes matrices:
    
    $$
    B = \begin{pmatrix}
    2 & 4 \\
    5 & -6
    \end{pmatrix}
    \hskip 1em 
    \text{y}
    \hskip 1em 
    C = \begin{pmatrix}
    9 & -3 \\
    3 & 6
    \end{pmatrix}
    $$
    
    a. Obtenga la suma de B + C.

In [0]:
B = np.array([2, 4, 5, -6]).reshape(2, 2)
C = np.array([9, -3, 3, 6]).reshape(2, 2)

B + C

array([[11,  1],
       [ 8,  0]])

    b. Obtenga el producto punto entre B y C.

In [0]:
np.dot(B, C)

array([[ 30,  18],
       [ 27, -51]])

## Ejercicios Intermedios

1. Utilizando un loop, genera una lista que almacene los valores de la tercera columna de la matriz A. 

In [0]:
lista_vacia = []

for i in range(3):
     lista_vacia.append(A[i,2])

lista_vacia

[2, 2, 1]

2. Use matrices para resolver los siguientes sistemas de ecuaciones:

    a. 
    $$
    \begin{aligned}
    a + b + c & = 6   \\
    3a - 2b + c & = 2 \\
    2a + b - c & = 1  
    \end{aligned}
    $$
    
    b.
    $$
    \begin{aligned}
    3a + 4b - 5c + d & = 10 \\
    2a + 2b + 2c - d & = 5  \\
    a - b + 5c - 5d & = 7   \\
    5a + d & = 4           
    \end{aligned}
    $$

In [0]:
# 2.a
a = np.array([1, 1, 1, 3, -2, 1, 2, 1, -1]).reshape(3,3)
b = np.array([6, 2, 1]).reshape(-1, 1)

print(np.linalg.solve(a,b))

[[1.]
 [2.]
 [3.]]


In [0]:
# 2.b
c = np.array([3, 4, -5, 1, 2, 2, 2, -1, 1, -1, 5, -5, 5, 0, 0, 1]).reshape(4,4)
d = np.array([10, 5, 7, 4]).reshape(-1, 1)
 
print(np.linalg.solve(c,d))

[[ 1.24778761]
 [ 1.01769912]
 [-0.88495575]
 [-2.23893805]]


## Ejercicios Avanzados

El estimador MCO minimiza la suma de los errores de predicción al cuadrado,
$\sum^{n}_{i=1}(Y_{i} - \beta_{0}X_{1i} - ... - \beta_{k}X_{ki})^2$. La fórmula del estimador MCO se obtiene tomando
la derivada de la suma de los errores de predicción al cuadrado respecto de cada elemento del vector de
coeficientes, igualando estas derivadas a cero y resolviendo para el estimador $\hat{\beta}$, se obtiene:

$$
\mathbf{\hat{\beta}} = (\mathbf{X'X})^{-1}\mathbf{X'Y}
$$

a. Utilizando la librería Pandas, importe la base de datos \dataset{Advertising.xlsx}, la que Consiste en el presupuesto gastado en publicidad (*TV*, *radio*, *newspaper*) de 200 productos. 

In [0]:
import pandas as pd

advertising = pd.read_csv('Advertising.csv')

b. Utilizando Numpy obtenga $\mathbf{\hat{\beta}}$ de la siguiente regresión:

$$
Sales_{i} = \beta_{0} + \beta_{1}TV_{i} + \varepsilon_{i}
$$    

In [0]:
# Utilizando solo numpy creamos la regresion sales ~ TV 
n = np.array(advertising.sales).size
y = np.array(advertising.sales).reshape(n, 1)
x = np.array(advertising.TV).reshape(n, 1)
X = np.append(np.ones([n, 1]), x, axis=1).reshape(n, 2)

X_inv = np.linalg.inv(np.dot(np.transpose(X),X))
X_trans_y = np.dot(np.transpose(X),y)
betas = np.dot(X_inv,X_trans_y)

In [0]:
# constate b0 
np.around(betas[0], 3)

array([7.033])

In [0]:
# coeficiente b1
np.around(betas[1], 3)

array([0.048])